"""The one word-splitting rule, shared by the index build and every lookup.

`phrase_index` is keyed on English phrases, so a lookup only finds precedent when the
incoming subtitle line is cut into words *exactly* as the corpus was. If the two sides
ever drift apart, every word carrying an apostrophe misses — silently, with no error and
no empty-result signal, just quietly worse translations. So both sides call this module
and nothing re-implements the rule.

An apostrophe **inside** a word is part of the word: ``What's up, dude?`` becomes
``["what's", "up", "dude"]``. Deleting it would merge contractions into unrelated English
words — ``we're`` into ``were``, ``i'll`` into ``ill`` — and blend two meanings that take
different Spanish under one key. See ``CORPUS.md`` §4 for the measured collision counts
and for why this is preferred over the Penn Treebank convention (``what`` + ``'s``).
"""

from __future__ import annotations

import re
from typing import Iterator, Sequence

#: Longest phrase the index holds, in words.
MAX_N = 4

#: Phrases rarer than this are dropped from the index as noise.
MIN_SUPPORT = 3

#: A word: letters, optionally carrying one internal apostrophe and more letters.
#: This literal is the single source of truth — the ClickHouse build derives its own
#: pattern from it via `clickhouse_tokens_sql`, so the two cannot diverge.
WORD_PATTERN = r"[a-z]+(?:'[a-z]+)?"

_WORD_RE = re.compile(WORD_PATTERN)

#: Apostrophes that real subtitle files use but the corpus does not. OPUS normalized
#: every quote to ASCII, so a `.srt` coming from a user must be folded before matching.
_APOSTROPHES = {
    "’": "'",  # right single quotation mark — the common typographic apostrophe
    "ʼ": "'",  # modifier letter apostrophe
    "′": "'",  # prime
    "`": "'",  # grave accent, used as an apostrophe in older subtitle files
    "´": "'",  # acute accent, likewise
}


def normalize(text: str) -> str:
    """Lowercase, and fold every apostrophe variant onto the ASCII one."""
    for variant, ascii_apostrophe in _APOSTROPHES.items():
        text = text.replace(variant, ascii_apostrophe)
    return text.lower()


def tokens(text: str) -> list[str]:
    """Cut a line into words. The inverse of nothing — this is lossy on purpose."""
    return _WORD_RE.findall(normalize(text))


def ngrams(words: Sequence[str], n: int) -> Iterator[str]:
    """Yield every run of exactly `n` consecutive words, space-joined."""
    if n < 1:
        raise ValueError(f"n must be >= 1, got {n}")
    for i in range(len(words) - n + 1):
        yield " ".join(words[i : i + n])


def phrases(text: str, max_n: int = MAX_N) -> Iterator[str]:
    """Yield every 1..max_n word phrase in a line — what a lookup searches the index for."""
    words = tokens(text)
    for n in range(1, max_n + 1):
        yield from ngrams(words, n)


def clickhouse_tokens_sql(column: str = "en") -> str:
    """The ClickHouse expression that tokenizes `column` the same way `tokens` does."""
    escaped = WORD_PATTERN.replace("'", "''")
    return f"extractAll(lowerUTF8({column}), '{escaped}')"


def phrase_index_sql(source: str = "subtext.mx_corpus", table: str = "subtext.phrase_index") -> str:
    """The full `phrase_index` build, generated so it cannot drift from `tokens`.

    Regenerate the checked-in file with ``python -m subtext.tokenizer > sql/phrase_index.sql``.
    """
    words = clickhouse_tokens_sql("en")
    header = f"""-- GENERATED by `python -m subtext.tokenizer` — do not edit by hand.
-- The tokenizer lives in src/subtext/tokenizer.py -- edit it there and regenerate,
-- so the index build and the lookup path can never disagree. See CORPUS.md §4.

DROP TABLE IF EXISTS {table};

CREATE TABLE {table}
(
  ng         String,
  n          UInt8,
  support    UInt32,
  ex_pair_id UInt64
) ENGINE = MergeTree ORDER BY (n, ng);
"""
    blocks = [header]
    for n in range(1, MAX_N + 1):
        if n == 1:
            ng = "arrayJoin(w)"
            guard = ""
        else:
            parts = ", ' ', ".join(f"w[i+{k}]" for k in range(n))
            parts = parts.replace("w[i+0]", "w[i]")
            ng = f"arrayJoin(arrayMap(i -> concat({parts}), range(1, length(w)-{n - 2})))" if n > 2 \
                 else f"arrayJoin(arrayMap(i -> concat({parts}), range(1, length(w))))"
            guard = f" WHERE length(w) >= {n}"
        blocks.append(f"""
INSERT INTO {table}
SELECT ng, {n} AS n, count() AS support, min(pair_id) AS ex_pair_id FROM (
  WITH {words} AS w
  SELECT pair_id, {ng} AS ng FROM {source}{guard}
) GROUP BY ng HAVING support >= {MIN_SUPPORT};
""")
    return "".join(blocks)


if __name__ == "__main__":
    print(phrase_index_sql(), end="")
