-- GENERATED by `python -m subtext.tokenizer` — do not edit by hand.
-- The tokenizer lives in src/subtext/tokenizer.py; edit it there and regenerate,
-- so the index build and the lookup path can never disagree. See CORPUS.md §4.

DROP TABLE IF EXISTS subtext.phrase_index;

CREATE TABLE subtext.phrase_index
(
  ng         String,
  n          UInt8,
  support    UInt32,
  ex_pair_id UInt64
) ENGINE = MergeTree ORDER BY (n, ng);

INSERT INTO subtext.phrase_index
SELECT ng, 1 AS n, count() AS support, min(pair_id) AS ex_pair_id FROM (
  WITH extractAll(lowerUTF8(en), '[a-z]+(?:''[a-z]+)?') AS w
  SELECT pair_id, arrayJoin(w) AS ng FROM subtext.mx_corpus
) GROUP BY ng HAVING support >= 3;

INSERT INTO subtext.phrase_index
SELECT ng, 2 AS n, count() AS support, min(pair_id) AS ex_pair_id FROM (
  WITH extractAll(lowerUTF8(en), '[a-z]+(?:''[a-z]+)?') AS w
  SELECT pair_id, arrayJoin(arrayMap(i -> concat(w[i], ' ', w[i+1]), range(1, length(w)))) AS ng FROM subtext.mx_corpus WHERE length(w) >= 2
) GROUP BY ng HAVING support >= 3;

INSERT INTO subtext.phrase_index
SELECT ng, 3 AS n, count() AS support, min(pair_id) AS ex_pair_id FROM (
  WITH extractAll(lowerUTF8(en), '[a-z]+(?:''[a-z]+)?') AS w
  SELECT pair_id, arrayJoin(arrayMap(i -> concat(w[i], ' ', w[i+1], ' ', w[i+2]), range(1, length(w)-1))) AS ng FROM subtext.mx_corpus WHERE length(w) >= 3
) GROUP BY ng HAVING support >= 3;

INSERT INTO subtext.phrase_index
SELECT ng, 4 AS n, count() AS support, min(pair_id) AS ex_pair_id FROM (
  WITH extractAll(lowerUTF8(en), '[a-z]+(?:''[a-z]+)?') AS w
  SELECT pair_id, arrayJoin(arrayMap(i -> concat(w[i], ' ', w[i+1], ' ', w[i+2], ' ', w[i+3]), range(1, length(w)-2))) AS ng FROM subtext.mx_corpus WHERE length(w) >= 4
) GROUP BY ng HAVING support >= 3;
