SELECT 'mx_corpus_refined' AS src, count() AS lines,
 countIf(multiSearchAny(t,[' orale ',' andale ',' andele ',' hijole ',' guey ',' wey ',' chido ',' chidos ',' padrisimo ',' chingon ',' chingona ',' chingar ',' chingada ',' chingado ',' chinga ',' chingue ',' chingo ',' pinche ',' pinches ',' pendejo ',' pendeja ',' pendejos ',' culero ',' culeros ',' naco ',' nacos ',' ahorita ',' ahoritita ',' platicar ',' platicamos ',' platicando ',' platica ',' platicas ',' mande ',' popote ',' popotes ',' chamba ',' chambear ',' chamaco ',' chamacos ',' chavo ',' chava ',' chavos ',' morro ',' morra ',' morros ',' neta ',' chale ',' gacho ',' gacha ',' chafa ',' fregon ',' fregona ',' desmadre ',' escuincle ',' escuincles ',' vato ',' vatos ',' tantito ',' tantita ',' luegito ',' manches ',' mames ',' apapachar ',' apapacho ',' alberca ',' albercas ',' banqueta ',' banquetas ',' elote ',' elotes ',' chamarra ',' chamarras ',' troca ',' trocas ',' jale ',' jalar ',' antojitos ',' botana ',' botanas ',' cuates ',' cuate ',' huevon ',' hueva ',' flojera ',' codo ',' lana ',' varo ',' feria ',' chingaderas ',' madrear ',' madriza ',' guacala ',' fuchi ',' zafo ',' sepa ',' nel ',' simon ',' chin ',' ándale '])) AS mx,
 countIf(multiSearchAny(t,[' vale ',' vales ',' tio ',' tia ',' tios ',' tias ',' joder ',' jodido ',' jodida ',' gilipollas ',' gilipolleces ',' vosotros ',' vuestro ',' vuestra ',' vuestros ',' vuestras ',' hostia ',' hostias ',' chaval ',' chavala ',' chavales ',' capullo ',' follar ',' cono ',' flipar ',' flipas ',' curro ',' currar ',' guay ',' majo ',' maja ',' pijo ',' pija ',' cutre ',' mola ',' molar ',' chorrada ',' aparcar ',' aparcamiento ',' alquilar ',' alquiler ',' billete ',' billetes ',' ascensor ',' gafas ',' patatas ',' melocoton ',' guisantes ',' judias ',' pajita ',' tarta ',' cazadora ',' fontanero ',' dormitorio ',' piso ',' pisos ',' zumo ',' ordenador ',' movil ',' moviles ',' coche ',' coches ',' cabreado ',' cabrear ',' mogollon ',' flipante '])) AS es_pen,
 countIf(multiSearchAny(t,[' boludo ',' boluda ',' pibe ',' piba ',' quilombo ',' parcero ',' parcera ',' chevere ',' bacano ',' chamo ',' pana ',' guagua ',' carajito ',' che ',' vos ',' chabon ',' laburo ',' laburar ',' pelotudo ',' forro ',' gil ',' posta ',' bondi ',' acha ',' vaina ',' broder ',' mae ',' tuanis '])) AS other_latam
FROM (SELECT concat(' ', replaceRegexpAll(translateUTF8(lowerUTF8(es),'áéíóúñüÁÉÍÓÚÑÜ','aeiounuaeiounu'), '[^a-z0-9]+', ' '), ' ') AS t FROM subtext.mx_corpus_refined)
UNION ALL
SELECT 'mx_corpus' AS src, count() AS lines,
 countIf(multiSearchAny(t,[' orale ',' andale ',' andele ',' hijole ',' guey ',' wey ',' chido ',' chidos ',' padrisimo ',' chingon ',' chingona ',' chingar ',' chingada ',' chingado ',' chinga ',' chingue ',' chingo ',' pinche ',' pinches ',' pendejo ',' pendeja ',' pendejos ',' culero ',' culeros ',' naco ',' nacos ',' ahorita ',' ahoritita ',' platicar ',' platicamos ',' platicando ',' platica ',' platicas ',' mande ',' popote ',' popotes ',' chamba ',' chambear ',' chamaco ',' chamacos ',' chavo ',' chava ',' chavos ',' morro ',' morra ',' morros ',' neta ',' chale ',' gacho ',' gacha ',' chafa ',' fregon ',' fregona ',' desmadre ',' escuincle ',' escuincles ',' vato ',' vatos ',' tantito ',' tantita ',' luegito ',' manches ',' mames ',' apapachar ',' apapacho ',' alberca ',' albercas ',' banqueta ',' banquetas ',' elote ',' elotes ',' chamarra ',' chamarras ',' troca ',' trocas ',' jale ',' jalar ',' antojitos ',' botana ',' botanas ',' cuates ',' cuate ',' huevon ',' hueva ',' flojera ',' codo ',' lana ',' varo ',' feria ',' chingaderas ',' madrear ',' madriza ',' guacala ',' fuchi ',' zafo ',' sepa ',' nel ',' simon ',' chin ',' ándale '])) AS mx,
 countIf(multiSearchAny(t,[' vale ',' vales ',' tio ',' tia ',' tios ',' tias ',' joder ',' jodido ',' jodida ',' gilipollas ',' gilipolleces ',' vosotros ',' vuestro ',' vuestra ',' vuestros ',' vuestras ',' hostia ',' hostias ',' chaval ',' chavala ',' chavales ',' capullo ',' follar ',' cono ',' flipar ',' flipas ',' curro ',' currar ',' guay ',' majo ',' maja ',' pijo ',' pija ',' cutre ',' mola ',' molar ',' chorrada ',' aparcar ',' aparcamiento ',' alquilar ',' alquiler ',' billete ',' billetes ',' ascensor ',' gafas ',' patatas ',' melocoton ',' guisantes ',' judias ',' pajita ',' tarta ',' cazadora ',' fontanero ',' dormitorio ',' piso ',' pisos ',' zumo ',' ordenador ',' movil ',' moviles ',' coche ',' coches ',' cabreado ',' cabrear ',' mogollon ',' flipante '])) AS es_pen,
 countIf(multiSearchAny(t,[' boludo ',' boluda ',' pibe ',' piba ',' quilombo ',' parcero ',' parcera ',' chevere ',' bacano ',' chamo ',' pana ',' guagua ',' carajito ',' che ',' vos ',' chabon ',' laburo ',' laburar ',' pelotudo ',' forro ',' gil ',' posta ',' bondi ',' acha ',' vaina ',' broder ',' mae ',' tuanis '])) AS other_latam
FROM (SELECT concat(' ', replaceRegexpAll(translateUTF8(lowerUTF8(es),'áéíóúñüÁÉÍÓÚÑÜ','aeiounuaeiounu'), '[^a-z0-9]+', ' '), ' ') AS t FROM subtext.mx_corpus);