DROP TABLE IF EXISTS subtext.win25;
CREATE TABLE subtext.win25 (b25 UInt32, n_rows UInt32, mx UInt32, latam UInt32, es UInt32, other UInt32)
ENGINE = MergeTree ORDER BY b25;
INSERT INTO subtext.win25
SELECT intDiv(pair_id, 25) AS b25,
       count() AS n_rows,
       countIf(multiSearchAny(t, [' orale ',' andale ',' andele ',' hijole ',' guey ',' wey ',' chido ',' chidos ',' padrisimo ',' chingon ',' chingona ',' chingar ',' chingada ',' chingado ',' chinga ',' chingue ',' chingo ',' pinche ',' pinches ',' pendejo ',' pendeja ',' pendejos ',' culero ',' culeros ',' naco ',' nacos ',' ahorita ',' ahoritita ',' platicar ',' platicamos ',' platicando ',' platica ',' platicas ',' mande ',' popote ',' popotes ',' chamba ',' chambear ',' chamaco ',' chamacos ',' chavo ',' chava ',' chavos ',' morro ',' morra ',' morros ',' neta ',' chale ',' gacho ',' gacha ',' chafa ',' fregon ',' fregona ',' desmadre ',' escuincle ',' escuincles ',' vato ',' vatos ',' tantito ',' tantita ',' luegito ',' manches ',' mames ',' apapachar ',' apapacho ',' alberca ',' albercas ',' banqueta ',' banquetas ',' elote ',' elotes ',' chamarra ',' chamarras ',' troca ',' trocas ',' jale ',' jalar ',' antojitos ',' botana ',' botanas ',' cuates ',' cuate ',' huevon ',' hueva ',' flojera ',' codo ',' lana ',' varo ',' feria ',' chingaderas ',' madrear ',' madriza ',' guacala ',' fuchi ',' zafo ',' sepa ',' nel ',' simon ',' chin ',' ándale ']))    AS mx,
       countIf(multiSearchAny(t, [' carro ',' carros ',' celular ',' celulares ',' computadora ',' computadoras ',' jugo ',' boleto ',' boletos ',' lentes ',' papas ',' departamento ',' departamentos ',' manejar ',' manejando ',' rentar ',' renta ',' checar ',' checa ',' estacionar ',' estacionamiento ',' elevador ',' recamara ',' plomero ',' durazno ',' chicharos ',' frijoles ',' cerillo ',' cerillos ',' ustedes ',' agarrar ',' platano ',' saco ',' valija '])) AS latam,
       countIf(multiSearchAny(t, [' vale ',' vales ',' tio ',' tia ',' tios ',' tias ',' joder ',' jodido ',' jodida ',' gilipollas ',' gilipolleces ',' vosotros ',' vuestro ',' vuestra ',' vuestros ',' vuestras ',' hostia ',' hostias ',' chaval ',' chavala ',' chavales ',' capullo ',' follar ',' cono ',' flipar ',' flipas ',' curro ',' currar ',' guay ',' majo ',' maja ',' pijo ',' pija ',' cutre ',' mola ',' molar ',' chorrada ',' aparcar ',' aparcamiento ',' alquilar ',' alquiler ',' billete ',' billetes ',' ascensor ',' gafas ',' patatas ',' melocoton ',' guisantes ',' judias ',' pajita ',' tarta ',' cazadora ',' fontanero ',' dormitorio ',' piso ',' pisos ',' zumo ',' ordenador ',' movil ',' moviles ',' coche ',' coches ',' cabreado ',' cabrear ',' mogollon ',' flipante ']))    AS es,
       countIf(multiSearchAny(t, [' boludo ',' boluda ',' pibe ',' piba ',' quilombo ',' parcero ',' parcera ',' chevere ',' bacano ',' chamo ',' pana ',' guagua ',' carajito ',' che ',' vos ',' chabon ',' laburo ',' laburar ',' pelotudo ',' forro ',' gil ',' posta ',' bondi ',' acha ',' vaina ',' broder ',' mae ',' tuanis '])) AS other
FROM (SELECT pair_id, concat(' ', replaceRegexpAll(translateUTF8(lowerUTF8(target_text),'áéíóúñüÁÉÍÓÚÑÜ','aeiounuaeiounu'), '[^a-z0-9]+', ' '), ' ') AS t FROM subtext.aligned_lines)
GROUP BY b25;
